trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    displayName: 'Build Application'

  - script: |
      npm test
    displayName: 'Run Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'drop'
    displayName: 'Publish Build Artifacts'
